general.import = [
    "~/dotfiles/config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 16

[font.normal]
family = "RobotoMono Nerd Font Mono"

[window]
opacity = 0.97

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
    { key = "Back", mods = "Control", chars = "\u0017" },  # Ctrl+Backspace to delete previous word
    { key = "Delete", mods = "Control", chars = "\u001b[3;5~" }  # Ctrl+Delete to delete next word
]

