# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[font]
size = 14

[font.normal]
family = "RobotoMono Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 5
y = 5
