import = [
    "~/dotfiles/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 10

[font.normal]
family = "RobotoMono Nerd Font"

[window]
opacity = 1

[window.padding]
x = 5
y = 5

